//USER CONSTANTS
export const AUTH_USER = "AUTH_USER";
export const LOGOUT_USER = "LOGOUT_USER";

//TEMPLATE CONSTANTS
export const ADD_TEMPLATE = "ADD_TEMPLATE";
export const REMOVE_TEMPLATE = "REMOVE_TEMPLATE";
export const UPDATE_TEMPLATE = "UPDATE_TEMPLATE";

//PATIENT CONSTANTS
export const ADD_PATIENT = "ADD_PATIENT";
export const REMOVE_PATIENT = "REMOVE_PATIENT";
export const UPDATE_PATIENT = "UPDATE_PATIENT";

//TEMPLATE FIELD CONSTANTS
export const ADD_FIELD = "ADD_FIELD";
export const REMOVE_FIELD = "REMOVE_FIELD";
export const UPDATE_FIELD = "UPDATE_FIELD";
export const REMOVE_TEMPLATE_FIELD = "REMOVE_TEMPLATE_FIELD";

//VISIT CONSTANTS
export const ADD_VISIT = "ADD_VISIT";
export const REMOVE_VISIT = "REMOVE_VISIT";
export const UPDATE_VISIT = "UPDATE_VISIT";
export const REMOVE_PATIENT_VISITS = "REMOVE_PATIENT_VISITS";

//FIELDMAP CONSTANTS
export const ADD_FIELDMAP = "ADD_FIELDMAP";
export const REMOVE_FIELDMAP = "REMOVE_FIELDMAP";
export const UPDATE_FIELDMAP = "UPDATE_FIELDMAP";
export const REMOVE_TEMPLATE_FIELDMAP = "REMOVE_TEMPLATE_FIELDMAP";
